sudo: false
install:
  - "pip install ."
  - "pip install virtualenv"
  - "pip install coveralls"
script:
  - "make test"
after_success: "if [ $TRAVIS_OS_NAME == linux ] ; then coveralls ; fi"
cache: pip
matrix:
    fast_finish: true
    include:
        - os: osx
          osx_image: xcode9.1
          language: generic
          env: HINT=Sierra
          before_install:
              - brew update
              - sleep 1
              - brew install python3
              - sleep 1
              - brew install pypy
              - sleep 1
              - pip3 install .
              - sleep 1
              - pip3 install virtualenv
              - sleep 1
              - pip_pypy install .
              - sleep 1
              - pip_pypy install virtualenv
              - sleep 1
        - os: linux
          python: 2.7
          language: python
        - os: linux
          python: 3.4
          language: python
        - os: linux
          python: 3.5
          language: python
        - os: linux
          python: 3.6
          language: python
        - os: linux
          python: 'nightly'
          language: python
        - os: linux
          python: pypy
          language: python
        - os: linux
          python: 'pypy3'
          language: python

    allow_failures:
        - python: "nightly"
        - python: 'pypy'
        - python: 'pypy3'
