sudo: false
os:
  - "linux"
  - "osx"
language: "python"
python:
  - "2.7"
  - "3.4"
  - "pypy"
  - "pypy3"
install:
  - "pip install ."
  - "pip install virtualenv"
  - "pip install coveralls"
script:
  - "make test"
after_success: "if [ $TRAVIS_OS_NAME == linux ] ; then coveralls ; fi"
matrix:
    allow_failures:
        - os: "osx"
